### ISSUE TITLE
Diagram klas

### ISSUE THREAD

**Issue by sovix234** [SharkSoft/Fat-Food#5]
Należy opracować diagram klas, który będzie niezbędny w etapie implementacji projektu.

**Comment by AdamKot34** [comment]
Dodałem diagram klas

**Comment by SharkSoft** [comment]
Należy stworzyć osobny folder na dokumentację i tam umieścić diagram klas oraz inne, przyszłe pliki. Folder powinien znajdować się w tym samym katalogu co folder Solution.

**Comment by AdamKot34** [comment]
Zrobione
